# Generated by Django 5.1.1 on 2024-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('patas', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Personas'},
        ),
    ]
