# Generated by Django 5.1.1 on 2024-10-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_animal_alter_categoria_options_alter_persona_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, help_text='En Dolares', max_digits=10)),
                ('peso', models.PositiveIntegerField(help_text='En Libras')),
                ('tipo', models.CharField(choices=[('virtual', 'Virtual'), ('fisico', 'Fisico')], default='virtual', max_length=50)),
                ('url', models.URLField(help_text='URL del libro')),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
