# Generated by Django 5.1.1 on 2024-10-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('virtual', 'virtual'), ('fisico', 'fisico')], default='virtual', max_length=50),
        ),
    ]
