# Generated by Django 5.1.1 on 2024-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_libro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.FloatField(default=1, help_text='En Dolares'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('virtual', 'virtual'), ('fisico', 'fisico')], default='virtual', max_length=7),
        ),
        migrations.AlterField(
            model_name='libro',
            name='url',
            field=models.URLField(default=None, help_text='URL del libro'),
        ),
    ]
