# Generated by Django 5.1.1 on 2024-10-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_libro_precio_alter_libro_tipo_alter_libro_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together={('nombre', 'tipo')},
        ),
    ]
