# Generated by Django 5.1.1 on 2024-10-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_padre_hijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('titular', models.CharField(max_length=50)),
                ('publicaciones', models.ManyToManyField(related_name='articulos', to='app1.publicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
