# Generated by Django 5.1.1 on 2024-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_empleado_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'el_nombre_que_se_guarda',
            },
        ),
    ]
