# Generated by Django 5.1.1 on 2024-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_nuevonombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevonombre',
            name='a',
            field=models.CharField(db_column='nombre_columna', default='', max_length=50),
        ),
    ]
