# Generated by Django 5.1.1 on 2024-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_nuevonombre_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
