# Generated by Django 5.1 on 2024-10-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_publicacion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
